FROM rust:1.72.1-buster as builder
WORKDIR /app
RUN cargo install mdbook
COPY book.toml /app
COPY . /app/src
# 把绝对路径改成 相对路径
RUN sed -i 's#](/#](./#g' src/SUMMARY.md

RUN mdbook build

FROM nginx
RUN rm -f /etc/localtime && \
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder /app/book /usr/share/nginx/html
