# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Determine Image Tag
      id: image_tag
      run: |
        # Check if it's a branch or tag, and set the image tag accordingly
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV  # main 分支使用 latest 标签
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          IMAGE_TAG=${GITHUB_REF#refs/tags/}  # 如果是标签，则使用标签名
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        else
          # 如果是其他分支，使用分支名作为标签
          IMAGE_TAG=${GITHUB_REF#refs/heads/}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        fi
        echo "Using image tag: $IMAGE_TAG"

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: gocheetah/cheetah:${{ env.IMAGE_TAG }}
        platforms: linux/amd64,linux/arm64
        file: Dockerfile  # 指定 Dockerfile 路径
